### ISSUE TITLE
Possible issue running extension under Python 2.7

### ISSUE THREAD

**Issue by markstuart** [qld-gov-au/ckanext-csrf-filter#14]
Hi @ThrawnCA, we've been running this extension against CKAN 2.9 and Python 2.7 while getting our many and varied extensions and dependencies Python 3 compatible.

Seeing this error in our logs currently:
```
ckan             | Traceback (most recent call last):
ckan             |   File "/usr/lib/ckan/venv/lib/python2.7/site-packages/flask/app.py", line 2449, in wsgi_app
ckan             |     response = self.handle_exception(e)
ckan             |   File "/usr/lib/ckan/venv/lib/python2.7/site-packages/flask/app.py", line 1866, in handle_exception
ckan             |     reraise(exc_type, exc_value, tb)
ckan             |   File "/usr/lib/ckan/venv/lib/python2.7/site-packages/flask/app.py", line 2446, in wsgi_app
ckan             |     response = self.full_dispatch_request()
ckan             |   File "/usr/lib/ckan/venv/lib/python2.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
ckan             |     return self.finalize_request(rv)
ckan             |   File "/usr/lib/ckan/venv/lib/python2.7/site-packages/flask/app.py", line 1969, in finalize_request
ckan             |     response = self.process_response(response)
ckan             |   File "/usr/lib/ckan/venv/lib/python2.7/site-packages/flask/app.py", line 2266, in process_response
ckan             |     response = handler(response)
ckan             |   File "/ckan_repo_code/src/ckanext-csrf-filter/ckanext/csrf_filter/plugin.py", line 89, in set_csrf_token
ckan             |     anti_csrf.apply_token(response)
ckan             |   File "/ckan_repo_code/src/ckanext-csrf-filter/ckanext/csrf_filter/anti_csrf.py", line 375, in apply_token
ckan             |     html = insert_token(html, token)
ckan             |   File "/ckan_repo_code/src/ckanext-csrf-filter/ckanext/csrf_filter/anti_csrf.py", line 362, in insert_token
ckan             |     html = CONFIRM_LINK_REVERSED.sub(insert_link_token, html)
ckan             | UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 654: ordinal not in range(128)
```

I haven't had time to investigate fully yet, wondered if you had any ideas?

**Comment by ThrawnCA** [comment]
Hmm. That line is just doing a regex string replacement. Does it definitely happen only on CKAN 2.7?

https://stackoverflow.com/questions/21129020/how-to-fix-unicodedecodeerror-ascii-codec-cant-decode-byte might be relevant. If it's a matter of mixing up string types, that would make some sense; CKAN 2.7 might well be using a different type for something.

**Comment by markstuart** [comment]
It's on CKAN 2.9.3 running Python 2.7 that we're seeing the issue, but possibly that `six.text_type(html)` idea will work, I'll take a look tomorrow 👍

**Comment by markstuart** [comment]
Apologies, this got left I don't recall if this solved the issue. It would be non-trivial now to get a test version running python 2.7 again for me, so I think I'll close this off.
